config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "top" => "animes#index"
  resources :animes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root  'animes#index'
end

app/models/anime.rb
class Anime < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :animes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: %i[ show edit update destroy ]
  
  # GET /animes or /animes.json
  def index
    #@animes = Anime.all
    @animes = current_user.animes
  end

  # GET /animes/1 or /animes/1.json
  def show
  end

  # GET /animes/new
  def new
    @anime = Anime.new
  end

  # GET /animes/1/edit
  def edit
  end

  # POST /animes or /animes.json
  def create
    @anime = Anime.new(anime_params)
    @anime.user = current_user

    respond_to do |format|
      if @anime.save
        format.html { redirect_to @anime, notice: "Anime was successfully created." }
        format.json { render :show, status: :created, location: @anime }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animes/1 or /animes/1.json
  def update
    respond_to do |format|
      if @anime.update(anime_params)
        format.html { redirect_to @anime, notice: "Anime was successfully updated." }
        format.json { render :show, status: :ok, location: @anime }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animes/1 or /animes/1.json
  def destroy
    @anime.destroy
    respond_to do |format|
      format.html { redirect_to animes_url, notice: "Anime was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime
      @anime = Anime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def anime_params
      params.require(:anime).permit(:name, :description, :body, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #oじゃなくてe
  before_action :authenticate_user!
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animes/_form.html.erb
<%= form_with(model: anime, local: true) do |form| %>
  <% if anime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

      <ul>
      <% anime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animes/edit.html.erb
<h1>Editing Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Show', @anime %> |
<%= link_to 'Back', animes_path %>

app/views/animes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Body</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animes.each do |anime| %>
      <tr>
        <td><%= anime.name %></td>
        <td><%= anime.description %></td>
        <td><%= anime.body %></td>
        <td><%= image_tag anime.image %></td>
        <td><%= link_to 'Show', anime %></td>
        <td><%= link_to 'Edit', edit_anime_path(anime) %></td>
        <td><%= link_to 'Destroy', anime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anime', new_anime_path %>

app/views/animes/new.html.erb
<h1>New Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Back', animes_path %>

app/views/animes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @anime.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @anime.description %>
</p>

<p>
  <strong>Body:</strong>
  <%= @anime.body %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @anime.image %>
</p>

<%= link_to 'Edit', edit_anime_path(@anime) %> |
<%= link_to 'Back', animes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <%= link_to "ログアウト",destroy_user_session_path,method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>